version: 2

project_name: scr

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"
  license: "MIT"
  homepage: "https://github.com/yarlson/scr"
  description: "Automated terminal screenshots. Script interactions, capture PNGs."
  maintainers:
    - "Yar Kravtsov <yarlson@gmail.com>"

snapshot:
  version_template: "0.0.0-{{ .Timestamp }}"

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{.Version}}
    flags:
      - -trimpath

archives:
  - name_template: >-
      scr_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    wrap_in_directory: true
    files:
      - README*
      - LICENSE*

checksum:
  name_template: "checksums.txt"

brews:
  - repository:
      owner: yarlson
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    skip_upload: "{{ with .Prerelease }}true{{ end }}"
    commit_author:
      name: "Yar Kravtsov"
      email: "yarlson@gmail.com"
    goarm: 7

changelog:
  sort: asc
  disable: "{{ .IsNightly }}"
  use: github
  filters:
    exclude:
      - "^chore"
      - "^docs"
      - "^test"

release:
  prerelease: auto
